***数据预处理***

In [19]:
#创建一个人工数据集，并存储在csv文件中 house_tiny是文件名 
import os
os.makedirs(os.path.join('D:\deeplearning','data'),exist_ok=True)
data_file=os.path.join('D:\deeplearning','data','house_tiny.csv')
with open (data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Pave,127500\n') #每行表示一个样本数据 NA表示未知
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [16]:
#安装pandas
!pip install pandas

In [20]:
#一般用pandas读取csv文件
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [21]:
#显示出来的是一个html文件
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

机器学习中最常用的就是处理缺失的数据。典型的方法有 ***插值和删除*** 

In [25]:
#这是插值
#iloc是一个索引器，按照位置进行选取
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
#inputs.mean()是对整数值求均值
#fillna是用括号中的均值填充缺失的值
inputs=inputs.fillna(inputs.mean())
inputs

C:\Users\18741\AppData\Local\Temp\ipykernel_4756\2538302186.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs=inputs.fillna(inputs.mean())


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [26]:
#非数值数据的补全
#get_dummies是特征提取，将特征抽象成N种不同的状态，one-hot编码
inputs=pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [28]:
#至此，已经将缺失的数值和字符补全，可以变成一个tensor,tensor中默认是float64,深度学习一般使用float32，计算块
import torch
x,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [29]:
#一般不要轻易改动没，可能会把其他东西也改了
a=torch.arange(12)
b=a.reshape(3,4)
b[:]=2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

tensor是一个数学上的张量概念，array是一个计算机的数组
python中如果这个变量后续没有被使用，会自动释放内存