***线性代数用代码实现***

In [2]:
#标量由只有一个元素的张量组成
import torch
x=torch.tensor([3.0])
y=torch.tensor([4.0])
x+y,x*y,x/y,x**y

(tensor([7.]), tensor([12.]), tensor([0.7500]), tensor([81.]))

In [3]:
#向量视为由标量组成的列表
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
#通过张量的索引来访问任一元素
x[3]

tensor(3)

In [5]:
#访问张量的长度
len(x)

4

In [6]:
#只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [7]:
#通过指定分量m和n来创建一个形状为m*n的矩阵
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
#矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
#对称矩阵 A等于A的转置
A=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
A==A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
#就像向量是标量的推广，矩阵是向量的推广，可以构建具有更多轴的数据结构
x=torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [17]:
#给定具有相同形状的任何两个张量，任何按元素二元运算的结果都是相同形状的张量
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()#通过分配新内存，将A的一个副本给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [18]:
#两个矩阵的按元素乘法称为 哈达玛积（Hadamard product) (数学符号一个⭕里面一个点)
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [20]:
#矩阵与标量的操作
a=2
A+2,A*2

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [28]:
#计算元素的和
x=torch.arange(40).reshape(2,5,4)
x,x.sum(),x.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor(780),
 torch.Size([2, 5, 4]))

***按照哪个维度求和，哪个维度就会消失，剩下剩余的维度***
***keepdims=True的话，求和的维度不会消失，会变成1**

In [69]:
import torch
a=torch.ones(2,5,4)
a.shape

torch.Size([2, 5, 4])

In [70]:
a.sum(dim=0).shape

torch.Size([5, 4])

In [74]:
a.sum(dim=0,keepdim=True).shape

torch.Size([1, 5, 4])

In [24]:
#按照指定轴求和  第一个二维矩阵的每行和第二个二维矩阵的每行相加
x.sum(dim=0),x.sum(dim=0).shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [26]:
#按照指定轴求和，每个二维矩阵各自按行相加
x.sum(dim=1),x.sum(dim=1).shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [27]:
#按照指定轴求和，每个二维矩阵各自按列相加
x.sum(dim=2),x.sum(dim=2).shape

(tensor([[  6,  22,  38,  54,  70],
         [ 86, 102, 118, 134, 150]]),
 torch.Size([2, 5]))

In [46]:
#平均值
x=torch.arange(12).reshape(3,4)
x,x.dtype

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.int64)

In [44]:
#先将x转换为float才能计算平均值
x=x.float()
x.mean()

tensor(5.5000)

In [45]:
#按照不同维度求均值
x.mean(dim=0)

tensor([4., 5., 6., 7.])

In [49]:
#计算总和或均值时保持轴数不变
x.sum(dim=1,keepdims=True)

tensor([[ 6],
        [22],
        [38]])

In [51]:
#用广播机制x除以x.sum  
x/x.sum(dim=1,keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [52]:
#累加求和，一行行滚下去
x.cumsum(dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21]])

In [55]:
#点积是相同位置的按元素乘积的和
#dtype=torch.float32是为了两个元素类型一致
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [57]:
#可以通过执行按元素乘法，然后求和就算两个向量的点积
torch.sum(x*y)

tensor(6.)

In [59]:
#矩阵向量乘积Ax
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [63]:
#矩阵相乘
B=torch.ones(4,3,dtype=torch.float32)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [64]:
#L2范数是向量元素平方和的平方根
u=torch.tensor([3.0,4.0])
torch.norm(u)

tensor(5.)

In [65]:
#L1范数，向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [68]:
#F范数，罗贝尼乌斯范数（Frobenius norm)是矩阵元素的平方和的平方根
torch.norm(torch.ones(4,9))

tensor(6.)